sex 10 jan 2025 00:20:33 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/void-maketar b/void-maketar
--- a/void-maketar
+++ b/void-maketar
@@ -2,13 +2,14 @@
 #shellcheck disable=SC2155,SC2034
 #shellcheck source=/dev/null
 
-#  void-maketar
+#  chili-maketar
 #  Description: Create tar of directories
 #
 #  Created: 2023/07/28
-#  Altered: 2024/03/08
+#  Altered: 2023/07/28
+#  Updated: 2024/12/25 - 03:42:08 -04 - Added gzip, xz, and normal tar support
 #
-#  Copyright (c) 2023-2024, Vilmar Catafesta <vcatafesta@gmail.com>
+#  Copyright (c) 2023-2023, Vilmar Catafesta <vcatafesta@gmail.com>
 #  All rights reserved.
 #
 #  Redistribution and use in source and binary forms, with or without
@@ -30,18 +31,19 @@
 #  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 #  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 #  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-#############################################################################
-#export LANGUAGE=en
-#export LANGUAGE=pt_BR
-export TEXTDOMAINDIR=/usr/share/locale
-export TEXTDOMAIN=void-maketar
+
+#debug
+export PS4='${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset}'
+#set -x
+#set -e
+shopt -s extglob
 
 readonly APP="${0##*/}"
-readonly _VERSION_="2.0.1-20240208"
-readonly DEPENDENCIES=(pigz tar tput sed)
+readonly _VERSION_="1.0.0-20230728"
+readonly DEPENDENCIES=(tar tput sed pigz pzstd xz gzip)
 
 function sh_diahora {
-#	DIAHORA=$(date +"%d%m%Y-%T" | sed 's/://g')
+	#	DIAHORA=$(date +"%d%m%Y-%T" | sed 's/://g')
 	DIAHORA=$(date +"%d%m%Y-%H:%M" | sed 's/://g')
 	printf "%s\n" "$DIAHORA"
 }
@@ -51,10 +53,12 @@ function sh_config {
 	declare -g CROSS="${white}[${COL_LIGHT_RED}✗${COL_NC}$white]"
 	declare -g BOOTLOG="/tmp/$APP-$(sh_diahora).log"
 	declare -g LOGGER='/dev/tty8'
-	declare -gi quiet=0
-	declare -g use_color=1
-	declare -gi contador=0
-	declare -gi njobs=1
+	declare -g quiet=false
+	declare -g use_color=true
+	declare -gi ncontador=1
+	declare -gi njobs=0
+	#declare -g compressor="normal" # Default compressor
+	declare -g compressor="pzstd" # Default compressor
 	sh_setvarcolors
 }
 
@@ -71,7 +75,11 @@ function cmdlogger {
 
 	info_msg "Running '$*'"
 	#   error_output=$( "$@" 2>&1 )
-	eval "$@" 2>&1 | tee -i -a "$BOOTLOG" >"$LOGGER"
+	if $quiet; then
+  	eval "$@" 2>&1 | tee -i -a "$BOOTLOG" >"$LOGGER"
+  else
+	  eval "$@" | tee -i -a "$BOOTLOG"
+	fi
 	#  status="${PIPESTATUS[0]}"
 	status="$?"
 	if [ $status -ne 0 ]; then
@@ -82,13 +90,13 @@ function cmdlogger {
 }
 
 function sh_check_terminal {
-	if [ ! -t 1 ]; then
-		use_color=0
+  if [ ! -t 1 ]; then
+		use_color=false
 	fi
 }
 
 function print_color {
-	if ((use_color)); then
+	if $use_color; then
 		echo -e "${@//\033\[*/}"
 	else
 		echo -e "$@"
@@ -97,7 +105,7 @@ function print_color {
 
 function sh_setvarcolors {
 	sh_check_terminal
-	if ((use_color)); then
+	if $use_color; then
 		bold=$(tput bold)
 		red=$(tput bold)$(tput setaf 196)
 		reset=$(tput sgr0)
@@ -111,89 +119,134 @@ function sh_setvarcolors {
 }
 
 die() {
-	printf "${red}$CROSS ${pink}%03d/%03d => ${red}$(gettext "FATAL:") %s\n\033[m" "$ncontador" "$njobs" "$@"
+	((++njobs))
+  printf "${red}$CROSS ${pink}%03d/%03d => ${red}FATAL: %s\n\033[m" "$ncontador" "$njobs" "$@"
+	((++ncontador))
 	exit 1
 }
 
 function info_msg() {
-	((++ncontador))
 	((++njobs))
 	printf "${green}$TICK ${pink}%03d/%03d => ${yellow}%s\n\033[m" "$ncontador" "$njobs" "$@"
+	((++ncontador))
 }
 
 function run_cmd {
-	info_msg "$APP: $(gettext "Rodando") $*"
+	info_msg "$APP: Running $*"
 	eval "$@"
 }
 
 function sh_checkDependencies() {
 	local d
-	local errorFound=0
+	local errorFound=false
 	declare -a missing
 
 	for d in "${DEPENDENCIES[@]}"; do
-		[[ -z $(command -v "$d") ]] && missing+=("$d") && errorFound=1 && info_msg "${red}$(gettext "ERRO: não consegui encontrar o comando")${reset}: ${cyan}'$d'${reset}"
+		[[ -z $(command -v "$d") ]] && missing+=("$d") && errorFound=true &&
+			info_msg "${red}ERRO: não encontrei o comando${reset}: ${cyan}'$d'${reset}"
 	done
 
-	if ((errorFound)); then
-		echo "${yellow}---------------$(gettext "IMPOSSÍVEL CONTINUAR")-------------${reset}"
-		echo "$(gettext "Este script precisa dos comandos listados acima")"
-		echo "$(gettext "Instale-os e/ou verifique se eles estão em seu") ${red}\$PATH${reset}"
-		echo "${yellow}---------------$(gettext "IMPOSSÍVEL CONTINUAR")-------------${reset}"
-		die "$(gettext "Instalação abortada!")"
+	if $errorFound; then
+		echo "${yellow}---------------IMPOSSIBLE TO CONTINUE-------------${reset}"
+		echo "This script needs the commands listed above"
+		echo "Install them and/or make sure they are in your ${red}\$PATH${reset}"
+		echo "${yellow}---------------IMPOSSIBLE TO CONTINUE-------------${reset}"
+		die "Installation aborted!"
 	fi
 }
 
 function sh_main {
-	local FILENAME=$1-$(sh_diahora).tar.gz
+  if [[ "$1" == '.' ]]; then
+    directory=$(basename "$(pwd)")
+  else
+    directory="${1%/}"
+  fi
+	local FILENAME=$directory-$(sh_diahora).tar
 	local error
+	local param='--verbose'
 
-	if ((quiet)); then
-		cmdlogger tar -I pigz --posix --xattrs -cf "$FILENAME" "$1"
-		error=$?
-	else
-		cmdlogger tar -I pigz --posix --xattrs -cvf "$FILENAME" "$1"
-		error=$?
-	fi
+  if $quiet; then
+    param=''
+  fi
+
+	case "$compressor" in
+	pigz)
+		FILENAME+=".gz"
+ 		cmdlogger tar -I pigz $param --posix --xattrs -chf "$FILENAME" "$1"
+		;;
+	pzstd)
+		FILENAME+=".zst"
+ 		cmdlogger tar -I pzstd $param --posix --xattrs -chf "$FILENAME" "$1"
+		;;
+	gzip)
+		FILENAME+=".gz"
+		cmdlogger tar -z $param --posix --xattrs -chf "$FILENAME" "$1"
+		;;
+	xz)
+		FILENAME+=".xz"
+		cmdlogger tar --xz $param --posix --xattrs -chf "$FILENAME" "$1"
+		;;
+	normal)
+		cmdlogger tar --posix $param --xattrs -chf "$FILENAME" "$1"
+		;;
+	esac
+
+	error=$?
+
 	if ((error)); then
 		die "$@"
 	else
-		info_msg "$FILENAME $(gettext "Criado com sucesso!")"
+		info_msg "Successfully created: ${red}$FILENAME ${reset}"
 	fi
 }
 
 sh_config
 sh_checkDependencies
 
-if [ "$(id -u)" -ne 0 ]; then
-	die "$APP: $(gettext "precisa de permissões de root para continuar, saindo.")"
+#if [ "$(id -u)" -ne 0 ]; then
+#	die "$APP: need root perms to continue, exiting."
+#fi
+if test -w "$PWD"; then
+  info_msg "$USER com gravação permitida em $PWD, prosseguindo..."
+else
+  info_msg "$USER sem permissão de gravação em $PWD"
+  if [ "$(id -u)" -ne 0 ]; then
+    die "$APP: need root perms to continue, exiting."
+  fi
+fi
+
+# Display usage information if no arguments are passed
+if [[ $# -eq 0 ]]; then
+  cat <<-EOF
+    Usage: $APP [options] <directory>
+    Options:
+      -q          Quiet mode (suppress progress messages)
+      -n          Disable colors in the output
+      -z          Use pigz for compression
+      -s          Use pzstd for compression ${cyan}(default)${reset}
+      -g          Use gzip for compression
+      -x          Use xz for compression
+      (normal)    Create tar archive without additional compression
+EOF
+  exit 1
 fi
 
 # Process command line options using getopts
-while getopts "qn" opt; do
-	case $opt in
-	q) quiet=1 ;;
-	n)
-		use_color=0
-		sh_setvarcolors
-		;;
-	\?)
-		echo "$(gettext "Opção inválida"): -$OPTARG" >&2
-		exit 1
-		;;
-	esac
+while getopts "qnsxzg" opt; do
+  case $opt in
+    q) quiet=true;info_msg 'Param -q detected, disabling verbose'             ;; # Quiet mode
+    n) use_color=false;sh_setvarcolors;info_msg 'Param -n detected, disabling colors';; # Disable color
+    z) compressor="pigz";info_msg "Param -z detected, compressor is now '$compressor'";; # Use pigz for compression
+    s) compressor="pzstd";info_msg "Param -z detected, compressor is now '$compressor'"     ;; # Use pzstd for compression
+    g) compressor="gzip";info_msg "Param -z detected, compressor is now '$compressor'"      ;; # Use gzip for compression
+    x) compressor="xz";info_msg "Param -z detected, compressor is now '$compressor'"        ;; # Use xz for compression
+    \?) die "Invalid option: -$OPTARG";;
+  esac
 done
-shift $((OPTIND - 1))
 
-if [ $# -ne 1 ]; then
-	cat <<-EOF
-		Usage: $APP [$(gettext "opções")] <$(gettext "diretório")>
-		$(gettext "opções:")
-		  -q          $(gettext "Modo silencioso (suprimir mensagens de progresso)")
-		  -n          $(gettext "Desativar cores na saída")
-	EOF
-	exit 1
-fi
+# Process the remaining argument (directory)
+shift $((OPTIND-1))
 
-[[ ! -d "$1" ]] && die "${cyan}$1${reset} $(gettext "não existe!")"
-sh_main "$@"
+# Check if the directory argument is missing or invalid
+[[ -z "$1" || ! -d "$1" ]] && die "${cyan}argument directory ${yellow}'$1' ${reset}is either missing or does not exist!"
+sh_main "$1"
